### ISSUE TITLE
add_urls_to_project require object id

### ISSUE THREAD

**Issue by Mte90** [rexsum420/django-nice#6]
So:

```
Config.add_urls_to_project(urlpatterns, app_label="core", model_name="User", field_name="email", object_id=1)
```

The object_id it should be not mandatory so the endpoint is generic and django-nice it should use the id passed by the code itself otherwise require to create an endpoint for all the ids available for any model...

```
bind_element_to_model(
            inputbox, app_label="core", model_name="User", object_id=user.id, fields=["email"], element_id="email"
        )
```

Already define the object_id so in Django we need to define that value as a placeholder.

**Comment by rexsum420** [comment]
Yea I think this is where I stopped messing with this repo because I couldn't get a solution that worked correctly
