### ISSUE TITLE
endpoints doesn't have any authentication

### ISSUE THREAD

**Issue by Mte90** [rexsum420/django-nice#8]
Right now any rest request is open to the world and not only for nicegui.

Looking at the code `ModelAPI` needs something to check that the authentication is fine.

**Comment by rexsum420** [comment]
You can can subclass the view and override the get and post functions with authentication required like this:

```
from module.views import ModelAPI
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse

class AuthenticatedView(ModelAPI):

    @method_decorator(login_required)
    def get(self, request, app_label, model_name, object_id, field_name):
        return super().get(request, app_label, model_name, object_id, field_name)

    @method_decorator(login_required)
    def post(self, request, app_label, model_name, object_id, field_name):
        return super().post(request, app_label, model_name, object_id, field_name)
```

**Comment by Mte90** [comment]
Maybe add that in the readme itself?

**Comment by Mte90** [comment]
Also looking at your readme and code to use `ModelAPI` isn't used at all to integrate django-nice but is used only internally.

Also in this way the authentication is Django side but on NiceGui side how we can do that?
For that reason I opened a ticket about login, so the login is on nicegui side using internally django, probably I will improve the PR I already opened.
